= 4. Настройка HTTP заголовков веб-приложения

=== About

source site is https://golangify.com/customizing-http-headers

==== Управление HTTP заголовками в Go

Существуют такие методы как _Set()_, _Add()_, _Del()_ и _Get()_, которые тоже можно использовать для добавления, удаления и чтения заголовков из карты:

[source,go]
----
// Устанавливаем новый заголовок управления кешем. Если заголовок "Cache-Control" уже указан, то он будет переписан.
w.Header().Set("Cache-Control", "public, max-age=31536000")

// Метод Add() добавляет новый заголовок "Cache-Control" и может вызываться несколько раз.
w.Header().Add("Cache-Control", "public")
w.Header().Add("Cache-Control", "max-age=31536000")

// Удаляем все значения из заголовка "Cache-Control".
w.Header().Del("Cache-Control")

// Получаем первое значение из заголовка "Cache-Control".
w.Header().Get("Cache-Control")
----

==== HTTP заголовки по умолчанию от веб-сервера

При отправке ответа, Go автоматически установит для вас три сгенерированных системой HTTP заголовка: *Date*, *Content-Length* и *Content-Type*.

Заголовок Content-Type (тип контента) весьма интересен. Go попытается автоматически узнать тип контента проанализировав содержимое тела ответа с помощью функции http.DetectContentType(). Если эта функция не сможет определить тип контента, Go укажет следующее значение для заголовка Content-Type: application/octet-stream.

Функция http.DetectContentType() обычно работает довольно неплохо. Однако главная проблема веб-разработчиков, плохо знакомыми с Go, заключается в том, что данная функция не может отличить JSON от обычного текста. По умолчанию, ответы содержащие JSON будут отправляться с заголовком Content-Type: text/plain; charset=utf-8. Вы можете предотвратить это, установив правильный заголовок вручную следующим образом:

[source, go]
----
w.Header().Set("Content-Type", "application/json")
w.Write([]byte(`{"name":"Alex"}`))
----

==== Обработка HTTP заголовка

Название заголовка не чувствительно к регистру. Когда вы используете методы Add(), Get(), Set() и Del() в карте заголовков, название заголовка всегда будет обработано с помощью функции textproto.CanonicalMIMEHeaderKey(). Эта функция преобразует первую букву и любую букву после дефиса в верхний регистр, а остальные буквы в нижний.

Если требуется избежать такого поведения, можно напрямую отредактировать базовую карту заголовков (у нее тип *map[string][]string*).

Кроме того, метод Del() не удаляет заголовки, сгенерированные системой по умолчанию. Чтобы подавить их, требуется напрямую получить доступ к базовой карте заголовков и указать значение nil для нужного вам заголовка.

[source, go]
----
w.Header()["X-XSS-Protection"] = []string{"1; mode=block"}

w.Header()["Date"] = nil
----