= 8. Получаем доступ к статическим файлам — CSS и JS

=== About

source site is https://golangify.com/serving-static-files

==== Особенности обработчика статических файлов

Обработчик статических файлов в Go обладает несколькими интересными особенностями, о которых стоит упомянуть:

- Он очищает все пути HTTP-запросов, запуская их через функцию path.Clean() перед тем как приступить к поиску запрашиваемого файла. Так удаляются потенциально опасные символы, такие как "." и ".." из URL, это поможет предотвратить атаки по обходу нижних уровней директорий. Эта функция особенно полезна, если вы используете статические файлы вместе с маршрутизатором, который не очищает URL пути в автоматическом порядке;

- Сегментирование HTTP запросов полностью поддерживаются. Это необходимо, если ваше веб-приложение предоставляет пользователям возможность скачивания больших файлов или вы предоставляете видео поток и требуется поддерживать возобновляемые загрузки. E. g.:

[source, bash]
----
$ curl -i -H "Range: bytes=100-199" --output - http://localhost:4000/static/img/logo.png
----

- Такие заголовки как *_Last-Modified_* и *_If-Modified-Since_* тоже поддерживаются. Если файл не изменился с момента последнего запроса пользователя, _http.FileServer_ отправит код состояния _304 Not Modified_ вместо самого файла, так как сам файл уже есть у клиента в кэше браузера. Это помогает уменьшить задержку и расходы на обработку запроса для клиента и для сервера;

- Заголовок *_Content-Type_* автоматически устанавливается в зависимости от расширения файла с помощью функции *_mime.TypeByExtension()_*. В зависимости от задачи, вы можете добавить свои собственные расширения и типы контента с помощью функции *_mime.AddExtensionType()_*

==== Обслуживание отдельных файлов

Иногда может потребоваться обслужить только один статический файл. Для этой задачи, функция *_http.ServeFile()_* используется следующим образом:

[source, go]
----
func downloadHandler(w http.ResponseWriter, r *http.Request) {
    http.ServeFile(w, r, "./ui/static/file.zip")
}
----

*Внимание:* Обработчик *_http.ServeFile()_* автоматически не очищает путь файла. Если вы указываете в данную функцию путь к файлу полученный от пользователя напрямую, во избежание атак обхода директории, перед использование этих данных, обязательно очистите их с помощью функции *_filepath.Clean()_*.

==== Ограничение просмотра файлов из директории

Есть несколько способов отключения просмотра списка файлов из директории. Какой самый простой?

Добавьте пустой файл _index.html_ в ту директорию, где требуется отключить вывод списка файлов. Веб-сервер всегда ищет сперва файл index.html, и пользователь увидит пустую страницу с кодом состояния 200 OK.

==== Настраиваемая имплементация файловой системы

Более сложным способом (однако он считается лучшим) является создание настраиваемой имплементации файловой системы http.FileSystem, с помощью которой будет возвращаться ошибка os.ErrNotExist для любого HTTP запроса напрямую к папке.